baseUrl: localhost:3000

port: 3000
secret: myuniversity

dbms: mysql

db:
  name: electronics
  host: localhost
  port: 3306
  user: xineman
  pass: air228

mysql:
  database: electronics
  host: localhost
  user: xineman
  password: air228

mongo:
  db: electronics
  host: localhost
  user: xineman
  pass: air228